// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessFiles(arg1) {
  return window['go']['main']['App']['ProcessFiles'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}
