// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ProcessFiles(arg1:Array<string>):Promise<Array<string>>;

export function SelectFiles():Promise<Array<string>>;
